language: go

os:
  - linux
  - osx
  - windows

go:
  - "1.15.x"  # latest

before_install:
  - go get ${gobuild_args} ./...

script:
  - go test ${gobuild_args} ./... -cover

before_deploy:
  - go build -o callhistory